[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
exclude = [
    "layers/",
    "venv/",
    ".venv/",
    "__pycache__/",
    ".git/",
]

[tool.ruff.lint]
ignore = ["E501"]  # Ignore line-too-long since black handles formatting
select = ["E", "F", "W"]  # Or whatever rules you want

[tool.pytest.ini_options]
addopts = "-q"